### PR TITLE
Adds support for Django 1.7

### PR DESCRIPTION
**Pull request by emiel**
A change in Django 1.7 resulted in different behavior from emitters.py
when serializing models. Django will now recognize fields by both their
name and attname (i.d. foo and foo_id).

  https://github.com/django/django/commit/c21e86ab9e3e5ebd6d245d038cb0cb352cd84c3a

To maintain the original behavior we detect if the field is directly
defined on the model (direct) is a related field and the allowed field
name (from icetea) ends in "_id". In this case we pretend the field does
not exist and maintain the old behavior.

An example of the desired behavior is as follows:

```
class FooHandler(ModelHandler):
    allowed_out_fields = ("contact", "contact_id")

Shoudl emit:

{
  "contact": {"id": 2, ...},
  "contact_id": 2
}
```

To aid in testing the following changes are included:

- Additional emitters.py tests
- Clean up sample test project
- Custom test runner (runtests.py)
- Django 1.7 migrations
- Removal of buildout support
- Support testing with tox against Django 1.6 & 1.7

### CODE REVIEW

**Comment by stargazer** [comment]
@emiel: I'm not sure I understand what problem we are trying to solve here. Could you explain a bit more or give me some relevant link?

**Comment by stargazer** [comment]
Nevermind @emiel I dug into the code and it's clear :)

**Comment by emiel** [comment]
Thanks for having a look @stargazer. :)

There is only one case in smartpr-api where this was an issue. In the Recipient handler, `contact_id` is in `allowed_out_fields`. The expected serialized form is something like `{ "contact_id" 23 }`. When switching to Django 1.7 the recipient was serialized as `{ "contact_id": { "id": 3 }}` because it now recognised 'contact_id' as a ForeignKey field and handled it as such.

Hopefully this change can get us through the smartpr-api Django upgrade and then we can ditch IceTea as soon as all endpoints have been ported to DRF.

**Comment by emiel** [comment]
Oh and I clarified the commit message a bit.

**Pull request merged**
